language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: test
      script: npm test

    - stage: coverage
      script: npm test && npm run coverage

    - stage: deploy
      deploy:
        provider: script
        script: echo "Publishing package on NPM" && npm run publish
        on:
          tags: true
