language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: test
      script: npm test

    - stage: coverage
      script: npm test && npm run coverage

    - stage: deploy
      script: echo "Publishing package on NPM" && npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_TOKEN"
        skip_cleanup: true
        on:
          tags: true
